
# nic2_connection_string = "Data Source=MSSNARIPAPP.frb.gov;initial Catalog=nic2_Application;Integrated Security=true"
# username      = "infobank"
# password      = "S361n0)ksja,made"
# connection_string = "sg-07e4f5ad51341741b"
domain                = ""
client_id             = ""
client_secret         = ""
authorization_level_id = ""
callback_path         = ""
